// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAql3CinJA__v3rT_y1mj-jr81e7AcaSoE',
    appId: '1:139653006528:web:f34e8330879606359e5925',
    messagingSenderId: '139653006528',
    projectId: 'marketplace-45dcc',
    authDomain: 'marketplace-45dcc.firebaseapp.com',
    storageBucket: 'marketplace-45dcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5732RjPRdXTtlgFmlRiUgNX080ZUPy3U',
    appId: '1:139653006528:android:98ee824de32d0a949e5925',
    messagingSenderId: '139653006528',
    projectId: 'marketplace-45dcc',
    storageBucket: 'marketplace-45dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1vHmyDpwuEOCvwZ1JTWVqHrJTaI67ilI',
    appId: '1:139653006528:ios:4398f92995d07c549e5925',
    messagingSenderId: '139653006528',
    projectId: 'marketplace-45dcc',
    storageBucket: 'marketplace-45dcc.appspot.com',
    iosBundleId: 'com.example.marketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1vHmyDpwuEOCvwZ1JTWVqHrJTaI67ilI',
    appId: '1:139653006528:ios:ac3904b2a3377a519e5925',
    messagingSenderId: '139653006528',
    projectId: 'marketplace-45dcc',
    storageBucket: 'marketplace-45dcc.appspot.com',
    iosBundleId: 'com.example.marketplace.RunnerTests',
  );
}
